#!/usr/bin/env bash

DIR=$HOME/bg
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swaybg -m fill -i ${DIR}/${RANDOMPICS} &
wal -i ${DIR}/${RANDOMPICS} &
notify-send "${RANDOMPICS}"

