#!/usr/bin/env bash

# Define base config directory
CONFIG_DIR="$HOME/.config/hypr/waybar"

# Define config and style paths
WAYBAR_CONFIG="$CONFIG_DIR/config"
WAYBAR_STYLE="$CONFIG_DIR/style.css"

# Run waybar with specified config and style
waybar -c "$WAYBAR_CONFIG" -s "$WAYBAR_STYLE"

